var my_Name = document.getElementById("name");
var title = document.getElementById("title");
var phone = document.getElementById("phone");
var email = document.getElementById("email");
var add = document.getElementById("add");
var pic = document.getElementById("pic");
var pass1 = document.getElementById("pass1");
var deg1 = document.getElementById("deg1");
var uni1 = document.getElementById("uni1");
var pass2 = document.getElementById("pass2");
var deg2 = document.getElementById("deg2");
var uni2 = document.getElementById("uni2");
var skill1 = document.getElementById("skill1");
var skill2 = document.getElementById("skill2");
var skill3 = document.getElementById("skill3");
var skill4 = document.getElementById("skill4");
var skill5 = document.getElementById("skill5");
var lang = document.getElementById("lang");
var lang2 = document.getElementById("lang2");
var styear1 = document.getElementById("styear1");
var styear2 = document.getElementById("styear2");
var styear3 = document.getElementById("styear3");
var endyear1 = document.getElementById("endyear1");
var endyear2 = document.getElementById("endyear2");
var endyear3 = document.getElementById("endyear3");
var company1 = document.getElementById("company1");
var company2 = document.getElementById("company2");
var company3 = document.getElementById("company3");
var complocation1 = document.getElementById("complocation1");
var complocation2 = document.getElementById("complocation2");
var complocation3 = document.getElementById("complocation3");
var jobTitle1 = document.getElementById("jobTitle1");
var jobTitle2 = document.getElementById("jobTitle2");
var jobTitle3 = document.getElementById("jobTitle3");
var achv1 = document.getElementById("achv1");
var achv2 = document.getElementById("achv2");
var achv3 = document.getElementById("achv3");
var achv4 = document.getElementById("achv4");
var achv5 = document.getElementById("achv5");
var achv6 = document.getElementById("achv6");
var achv7 = document.getElementById("achv7");
var achv8 = document.getElementById("achv8");
var achv9 = document.getElementById("achv9");
var interest1 = document.getElementById("interest1");
var interest2 = document.getElementById("interest2");
var interest3 = document.getElementById("interest3");
var interest4 = document.getElementById("interest4");
var interest5 = document.getElementById("interest5");
var submitBtn = document.getElementById("submitBtn");
var form = document.getElementById("form");
form === null || form === void 0 ? void 0 : form.addEventListener("submit", function (e) {
    e.preventDefault();
    localStorage.setItem("name", my_Name.value);
    localStorage.setItem("title", title.value);
    localStorage.setItem("phone", phone.value);
    localStorage.setItem("email", email.value);
    localStorage.setItem("add", add.value);
    localStorage.setItem("pass1", pass1.value);
    localStorage.setItem("deg1", deg1.value);
    localStorage.setItem("uni1", uni1.value);
    localStorage.setItem("pass2", pass2.value);
    localStorage.setItem("deg2", deg2.value);
    localStorage.setItem("uni2", uni2.value);
    localStorage.setItem("skill1", skill1.value);
    localStorage.setItem("skill2", skill2.value);
    localStorage.setItem("skill3", skill3.value);
    localStorage.setItem("skill4", skill4.value);
    localStorage.setItem("skill5", skill5.value);
    localStorage.setItem("lang", lang.value);
    localStorage.setItem("lang2", lang2.value);
    localStorage.setItem("styear1", styear1.value);
    localStorage.setItem("endyear1", endyear1.value);
    localStorage.setItem("company1", company1.value);
    localStorage.setItem("complocation1", complocation1.value);
    localStorage.setItem("jobTitle1", jobTitle1.value);
    localStorage.setItem("achv1", achv1.value);
    localStorage.setItem("achv2", achv2.value);
    localStorage.setItem("achv3", achv3.value);
    localStorage.setItem("styear3", styear3.value);
    localStorage.setItem("endyear3", endyear3.value);
    localStorage.setItem("company3", company3.value);
    localStorage.setItem("complocation3", complocation3.value);
    localStorage.setItem("jobTitle3", jobTitle3.value);
    localStorage.setItem("achv7", achv7.value);
    localStorage.setItem("achv8", achv8.value);
    localStorage.setItem("achv9", achv9.value);
    localStorage.setItem("interest1", interest1.value);
    localStorage.setItem("interest2", interest2.value);
    localStorage.setItem("interest3", interest3.value);
    localStorage.setItem("interest4", interest4.value);
    localStorage.setItem("interest5", interest5.value);
    if (pic.files && pic.files[0]) {
        var reader_1 = new FileReader();
        reader_1.addEventListener("load", function () {
            var textImg = reader_1.result;
            localStorage.setItem("profile_pic", textImg);
            console.log(textImg);
        });
        reader_1.readAsDataURL(pic.files[0]);
    }
    window.location.href = "./resume/staticResume.html";
});
