var myName = localStorage.getItem("name");
window.addEventListener("load", function () {
    var title = localStorage.getItem("title");
    var phone = localStorage.getItem("phone");
    var email = localStorage.getItem("email");
    var add = localStorage.getItem("add");
    var pass1 = localStorage.getItem("pass1");
    var deg1 = localStorage.getItem("deg1");
    var uni1 = localStorage.getItem("uni1");
    var pass2 = localStorage.getItem("pass2");
    var deg2 = localStorage.getItem("deg2");
    var uni2 = localStorage.getItem("uni2");
    var skill1 = localStorage.getItem("skill1");
    var skill2 = localStorage.getItem("skill2");
    var skill3 = localStorage.getItem("skill3");
    var skill4 = localStorage.getItem("skill4");
    var skill5 = localStorage.getItem("skill5");
    var lang = localStorage.getItem("lang");
    var lang2 = localStorage.getItem("lang2");
    var styear1 = localStorage.getItem("styear1");
    var endyear1 = localStorage.getItem("endyear1");
    var company1 = localStorage.getItem("company1");
    var complocation1 = localStorage.getItem("complocation1");
    var jobTitle1 = localStorage.getItem("jobTitle1");
    var achv1 = localStorage.getItem("achv1");
    var achv2 = localStorage.getItem("achv2");
    var achv3 = localStorage.getItem("achv3");
    var styear3 = localStorage.getItem("styear3");
    var endyear3 = localStorage.getItem("endyear3");
    var company3 = localStorage.getItem("company3");
    var complocation3 = localStorage.getItem("complocation3");
    var jobTitle3 = localStorage.getItem("jobTitle3");
    var picture = localStorage.getItem("profile_pic");
    var achv7 = localStorage.getItem("achv7");
    var achv8 = localStorage.getItem("achv8");
    var achv9 = localStorage.getItem("achv9");
    var interest1 = localStorage.getItem("interest1");
    var interest2 = localStorage.getItem("interest2");
    var interest3 = localStorage.getItem("interest3");
    var interest4 = localStorage.getItem("interest4");
    var interest5 = localStorage.getItem("interest5");
    var resName = document.getElementById("resName");
    resName.textContent = myName;
    var resTitle = document.getElementById("resTitle");
    resTitle.textContent = title;
    var resPhone = document.getElementById("resPhone");
    resPhone.textContent = phone;
    var resEmail = document.getElementById("resEmail");
    resEmail.textContent = email;
    var resAdd = document.getElementById("resAdd");
    resAdd.textContent = add;
    var resPassYear = document.getElementById("resPassYear");
    resPassYear.textContent = pass1;
    var resEduSubject = document.getElementById("resEduSubject");
    resEduSubject.textContent = deg1;
    var resEduInstitute = document.getElementById("resEduInstitute");
    resEduInstitute.textContent = uni1;
    var resPassYear1 = document.getElementById("resPassYear1");
    resPassYear1.textContent = pass2;
    var resEduSubject1 = document.getElementById("resEduSubject1");
    resEduSubject1.textContent = deg2;
    var resEduInstitute1 = document.getElementById("resEduInstitute1");
    resEduInstitute1.textContent = uni2;
    var resSkill1 = document.getElementById("resSkill1");
    resSkill1.textContent = skill1;
    var resSkill2 = document.getElementById("resSkill2");
    resSkill2.textContent = skill2;
    var resSkill3 = document.getElementById("resSkill3");
    resSkill3.textContent = skill3;
    var resSkill4 = document.getElementById("resSkill4");
    resSkill4.textContent = skill4;
    var resSkill5 = document.getElementById("resSkill5");
    resSkill5.textContent = skill5;
    var resLang1 = document.getElementById("resLang1");
    resLang1.textContent = lang;
    var resLang2 = document.getElementById("resLang2");
    resLang2.textContent = lang2;
    var resStartExpYear = document.getElementById("resStartExpYear");
    resStartExpYear.textContent = styear1;
    var resEndExpYear = document.getElementById("resEndExpYear");
    resEndExpYear.textContent = endyear1;
    var resExpCompany = document.getElementById("resExpCompany");
    resExpCompany.textContent = company1;
    var resExpCompanyLocation = document.getElementById("resExpCompanyLocation");
    resExpCompanyLocation.textContent = complocation1;
    var resExpRole = document.getElementById("resExpRole");
    resExpRole.textContent = jobTitle1;
    var resAchv1 = document.getElementById("resAchv1");
    resAchv1.textContent = achv1;
    var resAchv2 = document.getElementById("resAchv2");
    resAchv2.textContent = achv2;
    var resAchv3 = document.getElementById("resAchv3");
    resAchv3.textContent = achv3;
    var resStartExpYear3 = document.getElementById("resStartExpYear3");
    resStartExpYear3.textContent = styear3;
    var resEndExpYear3 = document.getElementById("resEndExpYear3");
    resEndExpYear3.textContent = endyear3;
    var resExpCompany3 = document.getElementById("resExpCompany3");
    resExpCompany3.textContent = company3;
    var resExpCompanyLocation3 = document.getElementById("resExpCompanyLocation3");
    resExpCompanyLocation3.textContent = complocation3;
    var resExpRole3 = document.getElementById("resExpRole3");
    resExpRole3.textContent = jobTitle3;
    var resAchv7 = document.getElementById("resAchv7");
    resAchv7.textContent = achv7;
    var resAchv8 = document.getElementById("resAchv8");
    resAchv8.textContent = achv8;
    var resAchv9 = document.getElementById("resAchv9");
    resAchv9.textContent = achv9;
    var resInterest1 = document.getElementById("resInterest1");
    resInterest1.textContent = interest1;
    var resInterest2 = document.getElementById("resInterest2");
    resInterest2.textContent = interest2;
    var resInterest3 = document.getElementById("resInterest3");
    resInterest3.textContent = interest3;
    var resInterest4 = document.getElementById("resInterest4");
    resInterest4.textContent = interest4;
    var resInterest5 = document.getElementById("resInterest5");
    resInterest5.textContent = interest5;
    var resImg = document.getElementById("resImg");
    resImg.src = picture;
});
var print_btn = document.getElementById("print_btn");
print_btn === null || print_btn === void 0 ? void 0 : print_btn.addEventListener("click", function () {
    window.print();
});
var edit_btn = document.getElementById("edit_btn");
edit_btn === null || edit_btn === void 0 ? void 0 : edit_btn.addEventListener("click", function () {
    window.history.back();
});
var share_btn = document.getElementById("share_btn");
var anc = document.getElementById("anc");
var userName;
if (myName) {
    userName = myName.toLowerCase().replace(/\s+/g, "-");
}
else {
    userName = "user";
}
var baseURL = "http://127.0.0.1:5500/resume/staticResume.html";
var uniqueURL = "".concat(baseURL, "?/").concat(myName);
share_btn === null || share_btn === void 0 ? void 0 : share_btn.addEventListener("click", function () {
    anc === null || anc === void 0 ? void 0 : anc.setAttribute("href", uniqueURL);
});
var copy_btn = document.getElementById("copy_btn");
copy_btn === null || copy_btn === void 0 ? void 0 : copy_btn.addEventListener("click", function () {
    window.navigator.clipboard.writeText(uniqueURL).then(function () {
        alert("Copied successfully!!");
    });
});
